name: Container Build

on:
  push:
    branches: [ "main", "add_tags" ]
  pull_request:
    branches: [ "main", "add_tags" ]
  schedule:
    - cron: '0 2 * * *'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  BASE_IMAGE: node
  BASE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Registry Login
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Fetch Raw Tags Data
      run: |
        echo "Fetching raw tags data from Docker Hub..."
        curl -s https://registry.hub.docker.com/v2/repositories/library/${{ env.BASE_IMAGE }}/tags/ > raw_tags.json
        echo "Raw tags data fetched."

    - name: Get Base Image Tags
      id: get-base-tags
      run: |
        echo "Filtering tags..."
        grep -oP '"name":\s*"\K[0-9]+(\.[0-9]+)*(\.[0-9]+)?(?=")' raw_tags.json | sort -u > base_image_tags.txt
        echo "Filtered tags:"
        cat base_image_tags.txt

    - name: Upload Base Image Tags
      uses: actions/upload-artifact@v4
      with:
        name: base-image-tags
        path: base_image_tags.txt

    - name: Download Base Image Tags
      uses: actions/download-artifact@v4
      with:
        name: base-image-tags
        path: .

    - name: Build and Push with Original Tags
      run: |
        echo "Reading tags from file..."
        TAGS=$(cat base_image_tags.txt)
        echo "Tags to be processed: $TAGS"
        if [ -z "$TAGS" ]; then
          echo "No tags to process. Exiting."
          exit 1
        fi
        IFS=$'\n' read -d '' -r -a TAG_ARRAY < base_image_tags.txt
        for TAG in "${TAG_ARRAY[@]}"; do
          echo "Building and pushing image with tag: $TAG"
          docker build --build-arg NODE_TAG=$TAG -t "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$TAG" .
          docker push "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$TAG"
        done