name: Container Build

on:
  push:
    branches: [ "main", "add_tags" ]
  pull_request:
    branches: [ "main", "add_tags" ]
  schedule:
    - cron: '0 2 * * *'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  BASE_IMAGE: node
  BASE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Registry Login
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Base Image Tags
      id: get-base-tags
      run: |
        curl -s https://registry.hub.docker.com/v2/repositories/library/${{ env.BASE_IMAGE }}/tags/ | jq -r '.results[].name' > base_image_tags.txt
        echo "BASE_IMAGE_TAGS=$(cat base_image_tags.txt)" >> $GITHUB_ENV

    - name: Build and Push with Original Tags
      run: |
        TAGS=$(cat base_image_tags.txt | tr '\n' ',' | sed 's/,$//')
        IFS=',' read -r -a TAG_ARRAY <<< "$TAGS"
        for TAG in "${TAG_ARRAY[@]}"; do
          docker build -t "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$TAG" .
          docker push "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$TAG"
        done
